import { useEffect, useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
import { Center, Box, Button, Text, Flex, FormControl, FormLabel, FormErrorMessage, Input } from '@chakra-ui/react'

import firebaseConfig from '../../firebase-config.json'
import { initializeApp } from 'firebase/app'
import { getAuth, createUserWithEmailAndPassword, onAuthStateChanged } from 'firebase/auth'
import { getFirestore, collection, addDoc, doc, getDoc, setDoc, updateDoc } from 'firebase/firestore'
import { SignIn, SignUp } from '../firebase/methods'

const Home: NextPage = () => {
  const app = initializeApp(firebaseConfig)

  const [email, setEmail] = useState('')
  const [senha, setSenha] = useState('')
  const [name, setName] = useState('')
  const changeEmail = (event) => setEmail(event.target.value)
  const changePassword = (event) => setSenha(event.target.value)
  const changeName = (event) => setName(event.target.value)

  // const auth = getAuth()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Center>
          <div>TAIS OFF!!!</div>
          <Flex direction="column" gap="8px">
            <FormControl>
              <FormLabel>Nome</FormLabel>
              <Input type="text" onChange={changeName} id="name"></Input>
            </FormControl>

            <FormControl>
              <FormLabel>Email</FormLabel>
              <Input type="email" onChange={changeEmail} id="email"></Input>
              <FormErrorMessage>Insira um email válido</FormErrorMessage>
            </FormControl>

            <FormControl>
              <FormLabel>Senha</FormLabel>
              <Input type="password" onChange={changePassword} id="password"></Input>
              <FormErrorMessage>Não caga com a senha não...</FormErrorMessage>
            </FormControl>

            <Button type="submit" onClick={() => SignUp(email, senha, { displayName: name })} colorScheme="blue">
              Submit
            </Button>
          </Flex>

          <Box>
            <Text>Bem vbindo</Text>
            <Image
              width="200px"
              height="200px"
              src="https://media.tenor.com/images/3705aad154b22965c6723ac41e56415c/tenor.gif"
            ></Image>
          </Box>
        </Center>
      </main>
    </div>
  )
}

export default Home
